[global]
   workgroup = SIGPAU
   netbios name = NODO02
   passdb backend = ldapsam:ldap://127.0.0.1
   ldap suffix = dc=sigpau,dc=local
   ldap admin dn = cn=admin,dc=sigpau,dc=local
   domain master = no
   domain logons = yes
   ldapsam:trusted = yes
   ldapsam:editposix = no
   wins support = yes
