[global]
   workgroup = SIGPAU
   netbios name = NODO01
   passdb backend = ldapsam:ldap://127.0.0.1
   ldap suffix = dc=sigpau,dc=local
   ldap admin dn = cn=admin,dc=sigpau,dc=local
   domain master = yes
   domain logons = yes
   logon path = \\10.120.17.242\profiles\%U.V6
   wins support = yes
