[libdefaults]
    default_realm = SIGPAU.LAB
    dns_lookup_realm = false
    dns_lookup_kdc = true

[realms]
    SIGPAU.LAB = {
        kdc = 10.120.17.242
        admin_server = 10.120.17.242
    }

[domain_realm]
    .sigpau.lab = SIGPAU.LAB
    sigpau.lab = SIGPAU.LAB
