[sssd]
services = nss, pam
config_file_version = 2
domains = sigpau.lab, sigpau.local

[nss]
filter_users = root

[pam]

# ===== DOMINIO 1: Samba Active Directory =====
[domain/sigpau.lab]
id_provider = ad
auth_provider = ad
access_provider = ad
ad_domain = sigpau.lab
ad_server = 10.120.17.242
krb5_realm = SIGPAU.LAB
cache_credentials = True
fallback_homedir = /mnt/nas_profiles/%u
default_shell = /bin/bash
ldap_id_mapping = True
use_fully_qualified_names = False

# ===== DOMINIO 2: OpenLDAP (slapd en puerto 3389) =====
[domain/sigpau.local]
id_provider = ldap
auth_provider = ldap
access_provider = permit
ldap_uri = ldap://10.120.17.242:3389
ldap_search_base = dc=sigpau,dc=local
ldap_user_search_base = ou=people,dc=sigpau,dc=local
ldap_id_use_start_tls = False
ldap_tls_reqcert = never
ldap_default_bind_dn = cn=admin,dc=sigpau,dc=local
ldap_default_authtok = {{ VAULT_SECRET_LDAP }}
fallback_homedir = /mnt/nas_profiles/%u
default_shell = /bin/bash
ldap_schema = rfc2307
ldap_id_mapping = False
