[ldap_servers]
sigpau01 ansible_host=10.120.17.242 ansible_user=root
sigpau02 ansible_host=10.120.22.207 ansible_user=root

[nas]
nas_sigpau ansible_host=10.1.100.17 ansible_user=lautaro

[clients]
debian-client ansible_host=10.120.17.247 ansible_user=sysadmin

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_pass=Asdqwe123
ansible_become_pass=Asdqwe123
